In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from pandas import Series, DataFrame
import random

LOAD IRIS DATASET FROM SKELEARN

In [3]:
 #Load the iris dataset#
    iris = load_iris()

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [36]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
# Extract the data and target from the dataset#

In [10]:
X = iris.data
y = iris.target
species = iris.target_names[y]


In [11]:
# Combine the data, species into a single array#
data = np.column_stack((X, species))


In [12]:
## converting data into dataframe and assigning it to df1##
df1=pd.DataFrame(data)

In [13]:
# Assigning column names #
df1.columns = ['sepal_length', 'sepal_width', 'petal_length ', 'petal_width', 'species']


In [14]:
df1

sepal_length sepal_width petal_length  petal_width    species
0            5.1         3.5           1.4         0.2     setosa
1            4.9         3.0           1.4         0.2     setosa
2            4.7         3.2           1.3         0.2     setosa
3            4.6         3.1           1.5         0.2     setosa
4            5.0         3.6           1.4         0.2     setosa
..           ...         ...           ...         ...        ...
145          6.7         3.0           5.2         2.3  virginica
146          6.3         2.5           5.0         1.9  virginica
147          6.5         3.0           5.2         2.0  virginica
148          6.2         3.4           5.4         2.3  virginica
149          5.9         3.0           5.1         1.8  virginica

[150 rows x 5 columns]

In [15]:
### Saving df1 as "iris"#
# run this cell only once#
df1.to_csv("iris.csv", index = False) 

In [16]:
schema=np.dtype([("sepal_length", np.float16),
                 ("sepal_width", np.float16),
                 ("petal_length", np.float16),
                 ("petal_width", np.float16),
                 ("species",  "<U16")])

In [18]:
## Loading Iris dataset using numpy##
np_data = np.loadtxt("iris.csv", skiprows=1, dtype = schema, delimiter = ",")
np_data

array([(5.1, 3.5, 1.4, 0.2, 'setosa'), (4.9, 3. , 1.4, 0.2, 'setosa'),
       (4.7, 3.2, 1.3, 0.2, 'setosa'), (4.6, 3.1, 1.5, 0.2, 'setosa'),
       (5. , 3.6, 1.4, 0.2, 'setosa'), (5.4, 3.9, 1.7, 0.4, 'setosa'),
       (4.6, 3.4, 1.4, 0.3, 'setosa'), (5. , 3.4, 1.5, 0.2, 'setosa'),
       (4.4, 2.9, 1.4, 0.2, 'setosa'), (4.9, 3.1, 1.5, 0.1, 'setosa'),
       (5.4, 3.7, 1.5, 0.2, 'setosa'), (4.8, 3.4, 1.6, 0.2, 'setosa'),
       (4.8, 3. , 1.4, 0.1, 'setosa'), (4.3, 3. , 1.1, 0.1, 'setosa'),
       (5.8, 4. , 1.2, 0.2, 'setosa'), (5.7, 4.4, 1.5, 0.4, 'setosa'),
       (5.4, 3.9, 1.3, 0.4, 'setosa'), (5.1, 3.5, 1.4, 0.3, 'setosa'),
       (5.7, 3.8, 1.7, 0.3, 'setosa'), (5.1, 3.8, 1.5, 0.3, 'setosa'),
       (5.4, 3.4, 1.7, 0.2, 'setosa'), (5.1, 3.7, 1.5, 0.4, 'setosa'),
       (4.6, 3.6, 1. , 0.2, 'setosa'), (5.1, 3.3, 1.7, 0.5, 'setosa'),
       (4.8, 3.4, 1.9, 0.2, 'setosa'), (5. , 3. , 1.6, 0.2, 'setosa'),
       (5. , 3.4, 1.6, 0.4, 'setosa'), (5.2, 3.5, 1.5, 0.2, 'setosa'),
      

In [19]:
type(np_data)

numpy.ndarray

getting the first five  rows

In [20]:
np_data[:5]

array([(5.1, 3.5, 1.4, 0.2, 'setosa'), (4.9, 3. , 1.4, 0.2, 'setosa'),
       (4.7, 3.2, 1.3, 0.2, 'setosa'), (4.6, 3.1, 1.5, 0.2, 'setosa'),
       (5. , 3.6, 1.4, 0.2, 'setosa')],
      dtype=[('sepal_length', '<f2'), ('sepal_width', '<f2'), ('petal_length', '<f2'), ('petal_width', '<f2'), ('species', '<U16')])

In [21]:
np_data[:5]['sepal_length']

array([5.1, 4.9, 4.7, 4.6, 5. ], dtype=float16)

In [22]:
np_data[:5][['petal_length','species']]

array([(1.4, 'setosa'), (1.4, 'setosa'), (1.3, 'setosa'), (1.5, 'setosa'),
       (1.4, 'setosa')],
      dtype={'names': ['petal_length', 'species'], 'formats': ['<f2', '<U16'], 'offsets': [4, 8], 'itemsize': 72})

PANDAS

In [23]:
pd_data = pd.read_csv("iris.csv")

In [24]:
pd_data

sepal_length  sepal_width  petal_length   petal_width    species
0             5.1          3.5            1.4          0.2     setosa
1             4.9          3.0            1.4          0.2     setosa
2             4.7          3.2            1.3          0.2     setosa
3             4.6          3.1            1.5          0.2     setosa
4             5.0          3.6            1.4          0.2     setosa
..            ...          ...            ...          ...        ...
145           6.7          3.0            5.2          2.3  virginica
146           6.3          2.5            5.0          1.9  virginica
147           6.5          3.0            5.2          2.0  virginica
148           6.2          3.4            5.4          2.3  virginica
149           5.9          3.0            5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
type(pd_data)

pandas.core.frame.DataFrame

In [25]:
pd_data.head()

sepal_length  sepal_width  petal_length   petal_width species
0           5.1          3.5            1.4          0.2  setosa
1           4.9          3.0            1.4          0.2  setosa
2           4.7          3.2            1.3          0.2  setosa
3           4.6          3.1            1.5          0.2  setosa
4           5.0          3.6            1.4          0.2  setosa

In [26]:
pd_data.tail()

sepal_length  sepal_width  petal_length   petal_width    species
145           6.7          3.0            5.2          2.3  virginica
146           6.3          2.5            5.0          1.9  virginica
147           6.5          3.0            5.2          2.0  virginica
148           6.2          3.4            5.4          2.3  virginica
149           5.9          3.0            5.1          1.8  virginica

In [27]:
pd_data.head().sepal_length

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length, dtype: float64

In [29]:
pd_data.columns

Index(['sepal_length', 'sepal_width', 'petal_length ', 'petal_width',
       'species'],
      dtype='object')

In [30]:
pd_data.head().loc[:, ['petal_length ','species']]

petal_length  species
0            1.4  setosa
1            1.4  setosa
2            1.3  setosa
3            1.5  setosa
4            1.4  setosa

In [31]:
pd_data.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [33]:
##Converting to DataFrame##
np_pd_data = pd.DataFrame(np_data)

In [34]:
np_pd_data

sepal_length  sepal_width  petal_length  petal_width    species
0        5.101562     3.500000      1.400391     0.199951     setosa
1        4.898438     3.000000      1.400391     0.199951     setosa
2        4.699219     3.199219      1.299805     0.199951     setosa
3        4.601562     3.099609      1.500000     0.199951     setosa
4        5.000000     3.599609      1.400391     0.199951     setosa
..            ...          ...           ...          ...        ...
145      6.699219     3.000000      5.199219     2.300781  virginica
146      6.300781     2.500000      5.000000     1.900391  virginica
147      6.500000     3.000000      5.199219     2.000000  virginica
148      6.199219     3.400391      5.398438     2.300781  virginica
149      5.898438     3.000000      5.101562     1.799805  virginica

[150 rows x 5 columns]

Creating Series

In [40]:
ser1= Series([1,2,3,4])
ser2= Series(['a','b','c','d'])

In [41]:
print (ser1)

0    1
1    2
2    3
3    4
dtype: int64


In [42]:
print (ser2)

0    a
1    b
2    c
3    d
dtype: object


In [43]:
idx = pd.Index(["New York","Los Angeles","Chicago",
               "Houston","Philadephia", "Phoenix", "San Antonio",
               "San Diego", "Dallas"])

In [44]:
print (idx)

Index(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Philadephia',
       'Phoenix', 'San Antonio', 'San Diego', 'Dallas'],
      dtype='object')


In [45]:
pops = Series([8550,3972,2721,2296,1567,np.nan,1470,1395,1300],
             index=idx, name = "Populaion")

In [46]:
print (pops)

New York       8550.0
Los Angeles    3972.0
Chicago        2721.0
Houston        2296.0
Philadephia    1567.0
Phoenix           NaN
San Antonio    1470.0
San Diego      1395.0
Dallas         1300.0
Name: Populaion, dtype: float64


In [47]:
state = Series({'New York':'New York', 'Los Angeles': 'Califonia' , 
       'Phoenix': 'Arizona', 'San Antonio': 'Texas', 'San Diego': 'Califonia', 'Dallas': 'Texas'}, name = "State")

In [48]:
print (state)

New York        New York
Los Angeles    Califonia
Phoenix          Arizona
San Antonio        Texas
San Diego      Califonia
Dallas             Texas
Name: State, dtype: object


In [49]:
area= Series({'New York':302.6, 'Los Angeles': 468.7 , 
       'Philadephia':134.1,'Phoenix':516.7,'Austin':322.48}, name = "Area")

In [50]:
print(area)

New York       302.60
Los Angeles    468.70
Philadephia    134.10
Phoenix        516.70
Austin         322.48
Name: Area, dtype: float64


CREATING DATAFRAME

In [51]:
#FROM A NUMPY ARRAY#
mat=np.arange(0,9).reshape(3,3)

In [52]:
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
print(DataFrame(mat))

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


In [56]:
#ADDING LABELS#
print(DataFrame(mat, index=['a','b','c'],columns= ['alpha','beta','gamma']))

   alpha  beta  gamma
a      0     1      2
b      3     4      5
c      6     7      8


In [57]:
# What amounts to a 2D array (each tuple a row)#
arr = [(1,'a'),(2,'b'),(3,'c')]
print(arr)

[(1, 'a'), (2, 'b'), (3, 'c')]


In [58]:
print(DataFrame(arr, columns= ["Numbers", "Letters"]))

   Numbers Letters
0        1       a
1        2       b
2        3       c


In [61]:
# Creating from a dict#
print(DataFrame({"Numbers": [1,2,3], "Letters": ['a','b','c']}))

   Numbers Letters
0        1       a
1        2       b
2        3       c


NB if the value pairs dont have same length, it generates error

In [62]:
# Do we get an error#
DataFrame({"Numbers": ser1,"Letters":ser2})

Numbers Letters
0        1       a
1        2       b
2        3       c
3        4       d

In [63]:
print(DataFrame([pops,state,area]))

           New York Los Angeles  Chicago  Houston  Philadephia  Phoenix  \
Populaion    8550.0      3972.0   2721.0   2296.0       1567.0      NaN   
State      New York   Califonia      NaN      NaN          NaN  Arizona   
Area          302.6       468.7      NaN      NaN        134.1    516.7   

          San Antonio  San Diego  Dallas  Austin  
Populaion      1470.0     1395.0  1300.0     NaN  
State           Texas  Califonia   Texas     NaN  
Area              NaN        NaN     NaN  322.48  


In [64]:
print(DataFrame({'Population':pops, 'State':state, 'Area':area}))

             Population      State    Area
Austin              NaN        NaN  322.48
Chicago          2721.0        NaN     NaN
Dallas           1300.0      Texas     NaN
Houston          2296.0        NaN     NaN
Los Angeles      3972.0  Califonia  468.70
New York         8550.0   New York  302.60
Philadephia      1567.0        NaN  134.10
Phoenix             NaN    Arizona  516.70
San Antonio      1470.0      Texas     NaN
San Diego        1395.0  Califonia     NaN


In [65]:
print(DataFrame([pops,state,area]).T)

            Populaion      State    Area
New York       8550.0   New York   302.6
Los Angeles    3972.0  Califonia   468.7
Chicago        2721.0        NaN     NaN
Houston        2296.0        NaN     NaN
Philadephia    1567.0        NaN   134.1
Phoenix           NaN    Arizona   516.7
San Antonio    1470.0      Texas     NaN
San Diego      1395.0  Califonia     NaN
Dallas         1300.0      Texas     NaN
Austin            NaN        NaN  322.48


ADDING DATA

MOSTLY USED WHEN YOU FORGOT TO ADD A DATA INITIALLY

In [66]:
pops.append(Series({'Seattle':684, 'Denver':683}))

C:\Users\Digicap-LT1-04.35\AppData\Local\Temp\ipykernel_10532\3708587780.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pops.append(Series({'Seattle':684, 'Denver':683}))


New York       8550.0
Los Angeles    3972.0
Chicago        2721.0
Houston        2296.0
Philadephia    1567.0
Phoenix           NaN
San Antonio    1470.0
San Diego      1395.0
Dallas         1300.0
Seattle         684.0
Denver          683.0
dtype: float64

In [67]:
df = DataFrame([pops,state,area]).T
df.append(DataFrame({'Population': Series({'Seattle': 684,'Denver':683}),
                     'State': Series({'Seattle': 'Washington' ,'Denver': 'Colorado'}),
                     'Area': Series({'Seattle': np.nan,'Denver':np.nan})}))

C:\Users\Digicap-LT1-04.35\AppData\Local\Temp\ipykernel_10532\2650994870.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(DataFrame({'Population': Series({'Seattle': 684,'Denver':683}),


Populaion       State    Area  Population
New York       8550.0    New York   302.6         NaN
Los Angeles    3972.0   Califonia   468.7         NaN
Chicago        2721.0         NaN     NaN         NaN
Houston        2296.0         NaN     NaN         NaN
Philadephia    1567.0         NaN   134.1         NaN
Phoenix           NaN     Arizona   516.7         NaN
San Antonio    1470.0       Texas     NaN         NaN
San Diego      1395.0   Califonia     NaN         NaN
Dallas         1300.0       Texas     NaN         NaN
Austin            NaN         NaN  322.48         NaN
Seattle           NaN  Washington     NaN       684.0
Denver            NaN    Colorado     NaN       683.0

In [68]:
pd.concat([df,DataFrame({"Numbers": Series(np.arange(9), index = pops.index),
                        "Letters": Series(['a','c', 'd','h','l','n','p','p','s'],index = pops.index)})],
         axis=1)

Populaion      State    Area  Numbers Letters
New York       8550.0   New York   302.6      0.0       a
Los Angeles    3972.0  Califonia   468.7      1.0       c
Chicago        2721.0        NaN     NaN      2.0       d
Houston        2296.0        NaN     NaN      3.0       h
Philadephia    1567.0        NaN   134.1      4.0       l
Phoenix           NaN    Arizona   516.7      5.0       n
San Antonio    1470.0      Texas     NaN      6.0       p
San Diego      1395.0  Califonia     NaN      7.0       p
Dallas         1300.0      Texas     NaN      8.0       s
Austin            NaN        NaN  322.48      NaN     NaN

Saving DataFrames

In [69]:
## Run this only once#
df = DataFrame([pops,state,area]).T
# Saving data to csv file
#df.to_csv("cities.csv") # run only once

In [72]:
df

Populaion      State    Area
New York       8550.0   New York   302.6
Los Angeles    3972.0  Califonia   468.7
Chicago        2721.0        NaN     NaN
Houston        2296.0        NaN     NaN
Philadephia    1567.0        NaN   134.1
Phoenix           NaN    Arizona   516.7
San Antonio    1470.0      Texas     NaN
San Diego      1395.0  Califonia     NaN
Dallas         1300.0      Texas     NaN
Austin            NaN        NaN  322.48

In [73]:
df = DataFrame([pops,state,area])

In [74]:
df

New York Los Angeles  Chicago  Houston  Philadephia  Phoenix  \
Populaion    8550.0      3972.0   2721.0   2296.0       1567.0      NaN   
State      New York   Califonia      NaN      NaN          NaN  Arizona   
Area          302.6       468.7      NaN      NaN        134.1    516.7   

          San Antonio  San Diego  Dallas  Austin  
Populaion      1470.0     1395.0  1300.0     NaN  
State           Texas  Califonia   Texas     NaN  
Area              NaN        NaN     NaN  322.48

Subsetting your data


In [75]:
#Subsetting a series#
srs= Series(np.arange(5),
           index = ['alpha','beta','gamma','delta','epsilon'])
srs

alpha      0
beta       1
gamma      2
delta      3
epsilon    4
dtype: int32

In [76]:
srs[:2]

alpha    0
beta     1
dtype: int32

In [77]:
srs

alpha      0
beta       1
gamma      2
delta      3
epsilon    4
dtype: int32

In [78]:
srs[['beta','delta']]

beta     1
delta    3
dtype: int32

In [79]:
srs["beta":"delta"]

beta     1
gamma    2
delta    3
dtype: int32

In [80]:
srs[srs>3]

epsilon    4
dtype: int32

In [81]:
srs>3

alpha      False
beta       False
gamma      False
delta      False
epsilon     True
dtype: bool

In [82]:
srs2 = Series(['zero', 'one','two','three','four'],
             index = [3,2,4,0,1])
srs2

3     zero
2      one
4      two
0    three
1     four
dtype: object

In [84]:
 %pwd

'C:\\Users\\Digicap-LT1-04.35'